[project]
protostar-version = "0.7.0"
lib-path = "lib"
cairo-path = ["./lib/cairo_contracts/src"]

[contracts]
rental = ["src/libraries/rental.cairo"]
factory = ["src/libraries/rental_factory.cairo"]
nft = ["src/libraries/nft_contract.cairo"]
token = ["src/libraries/token.cairo"]

["profile.devnet.protostar.deploy"]
gateway-url="http://127.0.0.1:5050/"
chain-id="1536727068981429685321"
