[project]
protostar-version = "0.7.0"
lib-path = "lib"

[contracts]
rental = ["src/libraries/rental.cairo"]
factory = ["src/libraries/rental_factory.cairo"]
nft = ["src/libraries/nft_contract.cairo"]

[build]
cairo-path = ["./lib/cairo_contracts/src"]

