["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
rental = [
    "src/libraries/rental.cairo",
]
factory = [
    "src/libraries/rental_factory.cairo",
]
nft = [
    "src/libraries/nft_contract.cairo",
]

["protostar.build"]
cairo-path = ["./lib/cairo_contracts/src"]